# This is a basic workflow to help you get started with Actions

name: Update From Etherscan web

# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout repo - depth 1
        uses: actions/checkout@v2
      
      # setup python 3
      - name: Set up Python 3.8 🐍
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          
      # install dependencies
      - name: Install dependencies
        run: pip3 install -r requirements.txt
        working-directory: utils

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: python3 download_contracts_etherscan_io.py
        working-directory: utils
